#include <iostream>


/*
There are methods called special member functions:
- Default construcyot
- Copy constructor
- Copy asignment operator
- Destructor

Those can be generated by compiler if not provided.

delete keyword prevents compiler from generation of such methods
default keyword forces compiler to generate method if normaly it would not create it (e.g. if any constructor is provided, default constrctor will not be generated).
*/
class Test {

	Test() = default;
	Test(const Test&) = delete;

};

int main() {

	return 0;
}